export { default as Navbar } from "./navbar/Navbar";
export { default as Header } from "./header/Header";
export { default as Companies } from "./companies/Companies";
export { default as WGPT3 } from "./wgpt3/WGPT3";
export { default as Feature } from "./feature/Feature";
export { default as Intro } from "./intro/Intro";
export { default as CTA } from "./cta/CTA";
export { default as Blog } from "./blog/Blog";
export { default as Footer } from "./footer/Footer";